import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Manually ordered (not autogenerated) so the sidebar reads as a deliberate
// learning path: intro -> getting started -> core concepts -> language
// reference -> operational concerns -> tooling -> comparison/migration ->
// honesty pages (limitations/roadmap) -> the examples gallery last, since
// it's meant to be browsed after the reader already knows the vocabulary.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'getting-started',
    'core-concepts',
    {
      type: 'category',
      label: 'Language',
      items: [
        'language/syntax',
        'language/type-system',
        'language/grammar-reference',
      ],
    },
    'providers',
    'standard-library',
    'testing-and-evaluation',
    'debugging',
    'package-system',
    {
      type: 'category',
      label: 'Tooling',
      items: ['tooling/cli-reference', 'tooling/editor-support'],
    },
    'comparison',
    'migration-guides',
    'limitations',
    'roadmap',
    {
      type: 'category',
      label: 'Examples',
      link: {type: 'doc', id: 'examples/index'},
      items: [],
    },
  ],
};

export default sidebars;
